dependencies:
  - python-beautifulsoup
  - python-requests
  - python-html5lib
  - python-dogpile.cache (>= 0.5.2)
  - guessit
  - enzyme
  - babelfish
  - charade
  - pysrt
releases:
  - saucy
  - precise
  - quantal
  - raring
